//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbColaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbColaborador()
        {
            this.TbSolicitudCompra = new HashSet<TbSolicitudCompra>();
            this.TbSolicitudInsumo = new HashSet<TbSolicitudInsumo>();
        }
    
        public string IdColaborador { get; set; }
        public string NombreColaborador { get; set; }
        public string PrimerApellidoColaborador { get; set; }
        public string SegundoApellidoColaborador { get; set; }
        public string UserNameColaborador { get; set; }
        public string PasswordColaborador { get; set; }
        public Nullable<int> TipoColaborador { get; set; }
        public Nullable<bool> EstadoColaborador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbSolicitudCompra> TbSolicitudCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbSolicitudInsumo> TbSolicitudInsumo { get; set; }
    }
}
