//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbCompraSolicitudP
    {
        public int IdUnionCompra { get; set; }
        public string CodProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<bool> EstadoSolicitudCompra { get; set; }
        public string IdsolicitudCompra { get; set; }
    
        public virtual TbProducto TbProducto { get; set; }
        public virtual TbSolicitudCompra TbSolicitudCompra { get; set; }
    }
}
