//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbProductoInsumoS
    {
        public int IdSolicitudProducto { get; set; }
        public Nullable<int> IdSolictudInsumo { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> CantidadP { get; set; }
    
        public virtual TbProducto TbProducto { get; set; }
        public virtual TbSolicitudInsumo TbSolicitudInsumo { get; set; }
    }
}
