//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbProducto()
        {
            this.TbCompraSolicitudP = new HashSet<TbCompraSolicitudP>();
            this.TbProductoInsumoS = new HashSet<TbProductoInsumoS>();
        }
    
        public string CodProducto { get; set; }
        public string NombreProducto { get; set; }
        public Nullable<int> CantidadProducto { get; set; }
        public string CostoProducto { get; set; }
        public string Descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbCompraSolicitudP> TbCompraSolicitudP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbProductoInsumoS> TbProductoInsumoS { get; set; }
    }
}
