//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbPresupuesto
    {
        public string IdPresupuesto { get; set; }
        public Nullable<System.DateTime> MesPresupuesto { get; set; }
        public Nullable<double> MontoPresupuesto { get; set; }
        public Nullable<bool> EstadoPresupuesto { get; set; }
    }
}
