//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using CapaEntidades;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventarioEntities1 : DbContext
    {
        public inventarioEntities1()
            : base("name=inventarioEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TbColaborador> TbColaborador { get; set; }
        public virtual DbSet<TbCompraSolicitudP> TbCompraSolicitudP { get; set; }
        public virtual DbSet<TbPresupuesto> TbPresupuesto { get; set; }
        public virtual DbSet<TbProducto> TbProducto { get; set; }
        public virtual DbSet<TbProductoInsumoS> TbProductoInsumoS { get; set; }
        public virtual DbSet<TbSolicitudCompra> TbSolicitudCompra { get; set; }
        public virtual DbSet<TbSolicitudInsumo> TbSolicitudInsumo { get; set; }
    }
}
